//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorite
    {
        public int FavoriteID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> OffID { get; set; }
        public Nullable<int> OnID { get; set; }
    
        public virtual offline_education offline_education { get; set; }
        public virtual online_education online_education { get; set; }
        public virtual Users Users { get; set; }
    }
}
