//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class offline_education
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public offline_education()
        {
            this.Favorite = new HashSet<Favorite>();
        }
    
        public int OffID { get; set; }
        public string offName { get; set; }
        public Nullable<int> offSrok { get; set; }
        public Nullable<int> seats { get; set; }
        public Nullable<int> divisNum { get; set; }
        public string courseType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite> Favorite { get; set; }
    }
}
